-- Album admin migrations (idempotent)
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809165344_AddAlbumPhotoTags') THEN
    CREATE TABLE "Tags" (
      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "Name" character varying(200) NOT NULL,
      "Group" character varying(100) NULL
    );
    CREATE TABLE "FolderTags" (
      "FolderId" integer NOT NULL,
      "TagId" integer NOT NULL,
      CONSTRAINT "PK_FolderTags" PRIMARY KEY ("FolderId", "TagId"),
      CONSTRAINT "FK_FolderTags_Folders_FolderId" FOREIGN KEY ("FolderId") REFERENCES "Folders" ("Id") ON DELETE CASCADE,
      CONSTRAINT "FK_FolderTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
    );
    CREATE TABLE "PhotoTags" (
      "PhotoId" integer NOT NULL,
      "TagId" integer NOT NULL,
      CONSTRAINT "PK_PhotoTags" PRIMARY KEY ("PhotoId", "TagId"),
      CONSTRAINT "FK_PhotoTags_Photos_PhotoId" FOREIGN KEY ("PhotoId") REFERENCES "Photos" ("Id") ON DELETE CASCADE,
      CONSTRAINT "FK_PhotoTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
    );
    CREATE INDEX "IX_FolderTags_TagId" ON "FolderTags" ("TagId");
    CREATE INDEX "IX_PhotoTags_TagId" ON "PhotoTags" ("TagId");
    CREATE UNIQUE INDEX "IX_Tags_Name" ON "Tags" ("Name");
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260809165344_AddAlbumPhotoTags', '10.0.5');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809170213_AddTagNameNormalized') THEN
    DROP INDEX IF EXISTS "IX_Tags_Name";
    ALTER TABLE "Tags" ADD COLUMN IF NOT EXISTS "NameNormalized" character varying(200) NOT NULL DEFAULT '';
    UPDATE "Tags" SET "NameNormalized" = lower(btrim("Name"));
    CREATE UNIQUE INDEX "IX_Tags_NameNormalized" ON "Tags" ("NameNormalized");
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260809170213_AddTagNameNormalized', '10.0.5');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260809170600_AddPhotoExif') THEN
    CREATE TABLE "PhotoExifs" (
      "PhotoId" integer NOT NULL,
      "DateTaken" timestamp with time zone NULL,
      "CameraMake" character varying(200) NULL,
      "CameraModel" character varying(200) NULL,
      "Lens" character varying(200) NULL,
      "FocalLength" character varying(100) NULL,
      "Aperture" character varying(100) NULL,
      "ShutterSpeed" character varying(100) NULL,
      "Iso" integer NULL,
      "GpsLatitude" double precision NULL,
      "GpsLongitude" double precision NULL,
      "Artist" character varying(500) NULL,
      "Copyright" character varying(500) NULL,
      "ImageDescription" character varying(2000) NULL,
      "ExtraJson" text NULL,
      CONSTRAINT "PK_PhotoExifs" PRIMARY KEY ("PhotoId"),
      CONSTRAINT "FK_PhotoExifs_Photos_PhotoId" FOREIGN KEY ("PhotoId") REFERENCES "Photos" ("Id") ON DELETE CASCADE
    );
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20260809170600_AddPhotoExif', '10.0.5');
  END IF;
END $$;

COMMIT;

SELECT "MigrationId" FROM "__EFMigrationsHistory" WHERE "MigrationId" LIKE '20260809%' ORDER BY 1;
